### ISSUE TITLE
ErrorException: Template error: file_get_contents(https://corona.lmao.ninja/v2/all): failed to open stream: HTTP

### ISSUE THREAD

**Issue by Speddy** [boussaid/Corona#1]
ErrorException: Template error: file_get_contents(https://corona.lmao.ninja/v2/all): failed to open stream: HTTP request failed! HTTP/1.1 502 Bad Gateway src/addons/Corona/Widget/Corona.php:19 

    Generiert von: Unbekanntes Konto 19 Mai 2020 um 20:02 

Stack-Trace

#0 [internal function]: XF\Template\Templater->handleTemplateError(2, 'file_get_conten...', '/var/www/virtua...', 19, Array)
#1 src/addons/Corona/Widget/Corona.php(19): file_get_contents('https://corona....')
#2 internal_data/code_cache/widgets/_50_Corona.php(5): Corona\Widget\Corona->render()
#3 src/XF/Template/Templater.php(6681): XF\SubContainer\Widget->{closure}(Object(XENTR\ExternalLink\XF\Template\Templater), Array, Array)
#4 src/XF/SubContainer/Widget.php(168): XF\Template\Templater->renderWidgetClosure(Object(Closure), Array)
#5 src/XF/Template/Templater.php(1634): XF\SubContainer\Widget->getCompiledWidget(Array, Array)
#6 internal_data/code_cache/templates/l2/s4/public/forum_list.php(206): XF\Template\Templater->widgetPosition('forum_list_side...', Array)
#7 src/XF/Template/Templater.php(1315): XF\Template\Templater->{closure}(Object(XENTR\ExternalLink\XF\Template\Templater), Array)
#8 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('forum_list', Array)
#9 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
#10 src/XF/Mvc/Dispatcher.php(458): XF\Mvc\Renderer\Html->renderView('XF:Forum\\Listin...', 'public:forum_li...', Array)
#11 src/XF/Mvc/Dispatcher.php(440): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#12 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#13 src/XF/Mvc/Dispatcher.php(58): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#14 src/XF/App.php(2184): XF\Mvc\Dispatcher->run()
#15 src/XF.php(391): XF\App->run()
#16 index.php(20): XF::runApp('XF\\Pub\\App')
#17 {main}

Status der Anfrage

array(4) {
  ["url"] => string(1) "/"
  ["referrer"] => string(82) "http://www.host-tracker.com/UptimeGraph/Graph/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

**Comment by boussaid** [comment]
https://corona.lmao.ninja/docs/

**Comment by boussaid** [comment]
**OLD:** https://corona.lmao.ninja/v2/all
**New:** https://disease.sh/v2/all

**Comment by Speddy** [comment]
> **OLD:** https://corona.lmao.ninja/v2/all
> **New:** https://disease.sh/v2/all

Thanks.
